export const offerCards = [
  {
    name: "Nike shoe for sale",
    originalprice: "8000",
    offerprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeOne.png"],
  },
  {
    name: "Shoesdf f-efjeen ds",
    originalprice: "8000",
    offerprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeTwo.png"],
  },
  {
    name: "Shoesdf f-efjeen ds",
    originalprice: "8000",
    offerprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeThree.png"],
  },
  {
    name: "Nike shoe for sale",
    originalprice: "8000",
    offerprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeOne.png"],
  },
  {
    name: "Shoesdf f-efjeen ds",
    originalprice: "8000",
    offerprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeTwo.png"],
  },
  {
    name: "Shoesdf f-efjeen ds",
    originalprice: "8000",
    offerprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeThree.png"],
  },
  {
    name: "Nike shoe for sale",
    originalprice: "8000",
    offerprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeOne.png"],
  },
  {
    name: "Shoesdf f-efjeen ds",
    originalprice: "8000",
    offerprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeTwo.png"],
  },
  {
    name: "Shoesdf f-efjeen ds",
    originalprice: "8000",
    offerprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeThree.png"],
  },
  {
    name: "Nike shoe for sale",
    originalprice: "8000",
    offerprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeOne.png"],
  },
  {
    name: "Shoesdf f-efjeen ds",
    originalprice: "8000",
    offerprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeTwo.png"],
  },
  {
    name: "Shoesdf f-efjeen ds",
    originalprice: "8000",
    offerprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeThree.png"],
  },
];

export const productCards = [
  {
    name: "Nike shoe for sale",
    description: `Men's Sporty Gym Sneakers Breathable Anti-Slip Lace-Up/Slip-On High Top Winter Spring Autumn Fitness Jogging Mesh Rubber/EVA/PU`,
    minprice: "8000",
    category: "dfdfdf",
    maxprice: "5000",
    minOrder: "6",
    priceRange: [
      {
        rate: "307.81",
        from: "500",
        to: "1999",
      },
      {
        rate: "219.87",
        from: "2000",
        to: "9999",
      },
      {
        rate: "131.92",
        to: "10000",
      },
    ],
    stock: "15000",
    images: [
      "/src/assets/Images/products/firefly1.png",
      "/src/assets/Images/products/firefly2.png",
      "/src/assets/Images/products/firefly3.png",
      "/src/assets/Images/products/firefly4.png",
      "/src/assets/Images/products/firefly5.png",
      "/src/assets/Images/products/firefly6.png",
    ],
  },
  {
    name: "Shoesdf f-efjeen ds",
    minprice: "8000",
    maxprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeTwo.png"],
  },
  {
    name: "Shoesdf f-efjeen ds",
    minprice: "8000",
    maxprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeThree.png"],
  },
  {
    name: "Nike shoe for sale",
    minprice: "8000",
    maxprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeOne.png"],
  },
  {
    name: "Shoesdf f-efjeen ds",
    minprice: "8000",
    maxprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeTwo.png"],
  },
  {
    name: "Shoesdf f-efjeen ds",
    minprice: "8000",
    maxprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeThree.png"],
  },
  {
    name: "Nike shoe for sale",
    minprice: "8000",
    maxprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeOne.png"],
  },
  {
    name: "Shoesdf f-efjeen ds",
    minprice: "8000",
    maxprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeTwo.png"],
  },
  {
    name: "Shoesdf f-efjeen ds",
    minprice: "8000",
    maxprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeThree.png"],
  },
  {
    name: "Nike shoe for sale",
    minprice: "8000",
    maxprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeOne.png"],
  },
  {
    name: "Shoesdf f-efjeen ds",
    minprice: "8000",
    maxprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeTwo.png"],
  },
  {
    name: "Shoesdf f-efjeen ds",
    minprice: "8000",
    maxprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeThree.png"],
  },
];

export const newArrivalCards = [
  {
    name: "Nike shoe for sale",
    minprice: "8000",
    maxprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeOne.png"],
  },
  {
    name: "Shoesdf f-efjeen ds",
    minprice: "8000",
    maxprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeTwo.png"],
  },
  {
    name: "Shoesdf f-efjeen ds",
    minprice: "8000",
    maxprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeThree.png"],
  },
  {
    name: "Nike shoe for sale",
    minprice: "8000",
    maxprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeOne.png"],
  },
  {
    name: "Shoesdf f-efjeen ds",
    minprice: "8000",
    maxprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeTwo.png"],
  },
  {
    name: "Shoesdf f-efjeen ds",
    minprice: "8000",
    maxprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeThree.png"],
  },
  {
    name: "Nike shoe for sale",
    minprice: "8000",
    maxprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeOne.png"],
  },
  {
    name: "Shoesdf f-efjeen ds",
    minprice: "8000",
    maxprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeTwo.png"],
  },
  {
    name: "Shoesdf f-efjeen ds",
    minprice: "8000",
    maxprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeThree.png"],
  },
  {
    name: "Nike shoe for sale",
    minprice: "8000",
    maxprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeOne.png"],
  },
  {
    name: "Shoesdf f-efjeen ds",
    minprice: "8000",
    maxprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeTwo.png"],
  },
  {
    name: "Shoesdf f-efjeen ds",
    minprice: "8000",
    maxprice: "5000",
    minOrder: "6",
    images: ["/src/assets/Images/products/shoeThree.png"],
  },
];

export const cartee = {
  product: [
    {
      product: {
        name: "Nike shoe for sale",
        description: `Men's Sporty Gym Sneakers Breathable Anti-Slip Lace-Up/Slip-On High Top Winter Spring Autumn Fitness Jogging Mesh Rubber/EVA/PU`,
        minprice: "8000",
        maxprice: "5000",
        minOrder: "6",
        priceRange: [
          {
            rate: "307.81",
            from: "500",
            to: "1999",
          },
          {
            rate: "219.87",
            from: "2000",
            to: "9999",
          },
          {
            rate: "131.92",
            to: "10000",
          },
        ],
        stock: "15000",
        images: [
          "/src/assets/Images/products/firefly1.png",
          "/src/assets/Images/products/firefly2.png",
          "/src/assets/Images/products/firefly3.png",
          "/src/assets/Images/products/firefly4.png",
          "/src/assets/Images/products/firefly5.png",
          "/src/assets/Images/products/firefly6.png",
        ],
      },
      count: "10",
    },
    {
      product: {
        name: "Nike shoe for sale",
        description: `Men's Sporty Gym Sneakers Breathable Anti-Slip Lace-Up/Slip-On High Top Winter Spring Autumn Fitness Jogging Mesh Rubber/EVA/PU`,
        minprice: "8000",
        maxprice: "5000",
        minOrder: "6",
        priceRange: [
          {
            rate: "307.81",
            from: "500",
            to: "1999",
          },
          {
            rate: "219.87",
            from: "2000",
            to: "9999",
          },
          {
            rate: "131.92",
            to: "10000",
          },
        ],
        stock: "15000",
        images: [
          "/src/assets/Images/products/firefly1.png",
          "/src/assets/Images/products/firefly2.png",
          "/src/assets/Images/products/firefly3.png",
          "/src/assets/Images/products/firefly4.png",
          "/src/assets/Images/products/firefly5.png",
          "/src/assets/Images/products/firefly6.png",
        ],
      },
      count: "10",
    },
    {
      product: {
        name: "Nike shoe for sale",
        description: `Men's Sporty Gym Sneakers Breathable Anti-Slip Lace-Up/Slip-On High Top Winter Spring Autumn Fitness Jogging Mesh Rubber/EVA/PU`,
        minprice: "8000",
        maxprice: "5000",
        minOrder: "6",
        priceRange: [
          {
            rate: "307.81",
            from: "500",
            to: "1999",
          },
          {
            rate: "219.87",
            from: "2000",
            to: "9999",
          },
          {
            rate: "131.92",
            to: "10000",
          },
        ],
        stock: "15000",
        images: [
          "/src/assets/Images/products/firefly1.png",
          "/src/assets/Images/products/firefly2.png",
          "/src/assets/Images/products/firefly3.png",
          "/src/assets/Images/products/firefly4.png",
          "/src/assets/Images/products/firefly5.png",
          "/src/assets/Images/products/firefly6.png",
        ],
      },
      count: "10",
    },
    {
      product: {
        name: "Nike shoe for sale",
        description: `Men's Sporty Gym Sneakers Breathable Anti-Slip Lace-Up/Slip-On High Top Winter Spring Autumn Fitness Jogging Mesh Rubber/EVA/PU`,
        minprice: "8000",
        maxprice: "5000",
        minOrder: "6",
        priceRange: [
          {
            rate: "307.81",
            from: "500",
            to: "1999",
          },
          {
            rate: "219.87",
            from: "2000",
            to: "9999",
          },
          {
            rate: "131.92",
            to: "10000",
          },
        ],
        stock: "15000",
        images: [
          "/src/assets/Images/products/firefly1.png",
          "/src/assets/Images/products/firefly2.png",
          "/src/assets/Images/products/firefly3.png",
          "/src/assets/Images/products/firefly4.png",
          "/src/assets/Images/products/firefly5.png",
          "/src/assets/Images/products/firefly6.png",
        ],
      },
      count: "10",
    },
    {
      product: {
        name: "Nike shoe for sale",
        description: `Men's Sporty Gym Sneakers Breathable Anti-Slip Lace-Up/Slip-On High Top Winter Spring Autumn Fitness Jogging Mesh Rubber/EVA/PU`,
        minprice: "8000",
        maxprice: "5000",
        minOrder: "6",
        priceRange: [
          {
            rate: "307.81",
            from: "500",
            to: "1999",
          },
          {
            rate: "219.87",
            from: "2000",
            to: "9999",
          },
          {
            rate: "131.92",
            to: "10000",
          },
        ],
        stock: "15000",
        images: [
          "/src/assets/Images/products/firefly1.png",
          "/src/assets/Images/products/firefly2.png",
          "/src/assets/Images/products/firefly3.png",
          "/src/assets/Images/products/firefly4.png",
          "/src/assets/Images/products/firefly5.png",
          "/src/assets/Images/products/firefly6.png",
        ],
      },
      count: "10",
    },
    {
      product: {
        name: "Nike shoe for sale",
        description: `Men's Sporty Gym Sneakers Breathable Anti-Slip Lace-Up/Slip-On High Top Winter Spring Autumn Fitness Jogging Mesh Rubber/EVA/PU`,
        minprice: "8000",
        maxprice: "5000",
        minOrder: "6",
        priceRange: [
          {
            rate: "307.81",
            from: "500",
            to: "1999",
          },
          {
            rate: "219.87",
            from: "2000",
            to: "9999",
          },
          {
            rate: "131.92",
            to: "10000",
          },
        ],
        stock: "15000",
        images: [
          "/src/assets/Images/products/firefly1.png",
          "/src/assets/Images/products/firefly2.png",
          "/src/assets/Images/products/firefly3.png",
          "/src/assets/Images/products/firefly4.png",
          "/src/assets/Images/products/firefly5.png",
          "/src/assets/Images/products/firefly6.png",
        ],
      },
      count: "10",
    },
    {
      product: {
        name: "Nike shoe for sale",
        description: `Men's Sporty Gym Sneakers Breathable Anti-Slip Lace-Up/Slip-On High Top Winter Spring Autumn Fitness Jogging Mesh Rubber/EVA/PU`,
        minprice: "8000",
        maxprice: "5000",
        minOrder: "6",
        priceRange: [
          {
            rate: "307.81",
            from: "500",
            to: "1999",
          },
          {
            rate: "219.87",
            from: "2000",
            to: "9999",
          },
          {
            rate: "131.92",
            to: "10000",
          },
        ],
        stock: "15000",
        images: [
          "/src/assets/Images/products/firefly1.png",
          "/src/assets/Images/products/firefly2.png",
          "/src/assets/Images/products/firefly3.png",
          "/src/assets/Images/products/firefly4.png",
          "/src/assets/Images/products/firefly5.png",
          "/src/assets/Images/products/firefly6.png",
        ],
      },
      count: "10",
    },
    {
      product: {
        name: "Nike shoe for sale",
        description: `Men's Sporty Gym Sneakers Breathable Anti-Slip Lace-Up/Slip-On High Top Winter Spring Autumn Fitness Jogging Mesh Rubber/EVA/PU`,
        minprice: "8000",
        maxprice: "5000",
        minOrder: "6",
        priceRange: [
          {
            rate: "307.81",
            from: "500",
            to: "1999",
          },
          {
            rate: "219.87",
            from: "2000",
            to: "9999",
          },
          {
            rate: "131.92",
            to: "10000",
          },
        ],
        stock: "15000",
        images: [
          "/src/assets/Images/products/firefly1.png",
          "/src/assets/Images/products/firefly2.png",
          "/src/assets/Images/products/firefly3.png",
          "/src/assets/Images/products/firefly4.png",
          "/src/assets/Images/products/firefly5.png",
          "/src/assets/Images/products/firefly6.png",
        ],
      },
      count: "10",
    },
    {
      product: {
        name: "Nike shoe for sale",
        description: `Men's Sporty Gym Sneakers Breathable Anti-Slip Lace-Up/Slip-On High Top Winter Spring Autumn Fitness Jogging Mesh Rubber/EVA/PU`,
        minprice: "8000",
        maxprice: "5000",
        minOrder: "6",
        priceRange: [
          {
            rate: "307.81",
            from: "500",
            to: "1999",
          },
          {
            rate: "219.87",
            from: "2000",
            to: "9999",
          },
          {
            rate: "131.92",
            to: "10000",
          },
        ],
        stock: "15000",
        images: [
          "/src/assets/Images/products/firefly1.png",
          "/src/assets/Images/products/firefly2.png",
          "/src/assets/Images/products/firefly3.png",
          "/src/assets/Images/products/firefly4.png",
          "/src/assets/Images/products/firefly5.png",
          "/src/assets/Images/products/firefly6.png",
        ],
      },
      count: "10",
    },
    {
      product: {
        name: "Nike shoe for sale",
        description: `Men's Sporty Gym Sneakers Breathable Anti-Slip Lace-Up/Slip-On High Top Winter Spring Autumn Fitness Jogging Mesh Rubber/EVA/PU`,
        minprice: "8000",
        maxprice: "5000",
        minOrder: "6",
        priceRange: [
          {
            rate: "307.81",
            from: "500",
            to: "1999",
          },
          {
            rate: "219.87",
            from: "2000",
            to: "9999",
          },
          {
            rate: "131.92",
            to: "10000",
          },
        ],
        stock: "15000",
        images: [
          "/src/assets/Images/products/firefly1.png",
          "/src/assets/Images/products/firefly2.png",
          "/src/assets/Images/products/firefly3.png",
          "/src/assets/Images/products/firefly4.png",
          "/src/assets/Images/products/firefly5.png",
          "/src/assets/Images/products/firefly6.png",
        ],
      },
      count: "10",
    },
    {
      product: {
        name: "Nike shoe for sale",
        description: `Men's Sporty Gym Sneakers Breathable Anti-Slip Lace-Up/Slip-On High Top Winter Spring Autumn Fitness Jogging Mesh Rubber/EVA/PU`,
        minprice: "8000",
        maxprice: "5000",
        minOrder: "6",
        priceRange: [
          {
            rate: "307.81",
            from: "500",
            to: "1999",
          },
          {
            rate: "219.87",
            from: "2000",
            to: "9999",
          },
          {
            rate: "131.92",
            to: "10000",
          },
        ],
        stock: "15000",
        images: [
          "/src/assets/Images/products/firefly1.png",
          "/src/assets/Images/products/firefly2.png",
          "/src/assets/Images/products/firefly3.png",
          "/src/assets/Images/products/firefly4.png",
          "/src/assets/Images/products/firefly5.png",
          "/src/assets/Images/products/firefly6.png",
        ],
      },
      count: "10",
    },
  ],
  offerPrice: {},
  totalPrice: "₹ 505050505",
};

export const cart = [
  {
    product: {
      name: "Nike shoe for sale",
      description: `Men's Sporty Gym Sneakers Breathable Anti-Slip Lace-Up/Slip-On High Top Winter Spring Autumn Fitness Jogging Mesh Rubber/EVA/PU`,
      minprice: "8000",
      maxprice: "5000",
      minOrder: "6",
      priceRange: [
        {
          rate: "307.81",
          from: "500",
          to: "1999",
        },
        {
          rate: "219.87",
          from: "2000",
          to: "9999",
        },
        {
          rate: "131.92",
          to: "10000",
        },
      ],
      stock: "15000",
      images: [
        "/src/assets/Images/products/firefly1.png",
        "/src/assets/Images/products/firefly2.png",
        "/src/assets/Images/products/firefly3.png",
        "/src/assets/Images/products/firefly4.png",
        "/src/assets/Images/products/firefly5.png",
        "/src/assets/Images/products/firefly6.png",
      ],
    },
    count: "10",
  },
  {
    product: {
      name: "Nike shoe for sale",
      description: `Men's Sporty Gym Sneakers Breathable Anti-Slip Lace-Up/Slip-On High Top Winter Spring Autumn Fitness Jogging Mesh Rubber/EVA/PU`,
      minprice: "8000",
      maxprice: "5000",
      minOrder: "6",
      priceRange: [
        {
          rate: "307.81",
          from: "500",
          to: "1999",
        },
        {
          rate: "219.87",
          from: "2000",
          to: "9999",
        },
        {
          rate: "131.92",
          to: "10000",
        },
      ],
      stock: "15000",
      images: [
        "/src/assets/Images/products/firefly1.png",
        "/src/assets/Images/products/firefly2.png",
        "/src/assets/Images/products/firefly3.png",
        "/src/assets/Images/products/firefly4.png",
        "/src/assets/Images/products/firefly5.png",
        "/src/assets/Images/products/firefly6.png",
      ],
    },
    count: "10",
  },
  {
    product: {
      name: "Nike shoe for sale",
      description: `Men's Sporty Gym Sneakers Breathable Anti-Slip Lace-Up/Slip-On High Top Winter Spring Autumn Fitness Jogging Mesh Rubber/EVA/PU`,
      minprice: "8000",
      maxprice: "5000",
      minOrder: "6",
      priceRange: [
        {
          rate: "307.81",
          from: "500",
          to: "1999",
        },
        {
          rate: "219.87",
          from: "2000",
          to: "9999",
        },
        {
          rate: "131.92",
          to: "10000",
        },
      ],
      stock: "15000",
      images: [
        "/src/assets/Images/products/firefly1.png",
        "/src/assets/Images/products/firefly2.png",
        "/src/assets/Images/products/firefly3.png",
        "/src/assets/Images/products/firefly4.png",
        "/src/assets/Images/products/firefly5.png",
        "/src/assets/Images/products/firefly6.png",
      ],
    },
    count: "10",
  },
  {
    product: {
      name: "Nike shoe for sale",
      description: `Men's Sporty Gym Sneakers Breathable Anti-Slip Lace-Up/Slip-On High Top Winter Spring Autumn Fitness Jogging Mesh Rubber/EVA/PU`,
      minprice: "8000",
      maxprice: "5000",
      minOrder: "6",
      priceRange: [
        {
          rate: "307.81",
          from: "500",
          to: "1999",
        },
        {
          rate: "219.87",
          from: "2000",
          to: "9999",
        },
        {
          rate: "131.92",
          to: "10000",
        },
      ],
      stock: "15000",
      images: [
        "/src/assets/Images/products/firefly1.png",
        "/src/assets/Images/products/firefly2.png",
        "/src/assets/Images/products/firefly3.png",
        "/src/assets/Images/products/firefly4.png",
        "/src/assets/Images/products/firefly5.png",
        "/src/assets/Images/products/firefly6.png",
      ],
    },
    count: "10",
  },
  {
    product: {
      name: "Nike shoe for sale",
      description: `Men's Sporty Gym Sneakers Breathable Anti-Slip Lace-Up/Slip-On High Top Winter Spring Autumn Fitness Jogging Mesh Rubber/EVA/PU`,
      minprice: "8000",
      maxprice: "5000",
      minOrder: "6",
      priceRange: [
        {
          rate: "307.81",
          from: "500",
          to: "1999",
        },
        {
          rate: "219.87",
          from: "2000",
          to: "9999",
        },
        {
          rate: "131.92",
          to: "10000",
        },
      ],
      stock: "15000",
      images: [
        "/src/assets/Images/products/firefly1.png",
        "/src/assets/Images/products/firefly2.png",
        "/src/assets/Images/products/firefly3.png",
        "/src/assets/Images/products/firefly4.png",
        "/src/assets/Images/products/firefly5.png",
        "/src/assets/Images/products/firefly6.png",
      ],
    },
    count: "10",
  },
  {
    product: {
      name: "Nike shoe for sale",
      description: `Men's Sporty Gym Sneakers Breathable Anti-Slip Lace-Up/Slip-On High Top Winter Spring Autumn Fitness Jogging Mesh Rubber/EVA/PU`,
      minprice: "8000",
      maxprice: "5000",
      minOrder: "6",
      priceRange: [
        {
          rate: "307.81",
          from: "500",
          to: "1999",
        },
        {
          rate: "219.87",
          from: "2000",
          to: "9999",
        },
        {
          rate: "131.92",
          to: "10000",
        },
      ],
      stock: "15000",
      images: [
        "/src/assets/Images/products/firefly1.png",
        "/src/assets/Images/products/firefly2.png",
        "/src/assets/Images/products/firefly3.png",
        "/src/assets/Images/products/firefly4.png",
        "/src/assets/Images/products/firefly5.png",
        "/src/assets/Images/products/firefly6.png",
      ],
    },
    count: "10",
  },
  {
    product: {
      name: "Nike shoe for sale",
      description: `Men's Sporty Gym Sneakers Breathable Anti-Slip Lace-Up/Slip-On High Top Winter Spring Autumn Fitness Jogging Mesh Rubber/EVA/PU`,
      minprice: "8000",
      maxprice: "5000",
      minOrder: "6",
      priceRange: [
        {
          rate: "307.81",
          from: "500",
          to: "1999",
        },
        {
          rate: "219.87",
          from: "2000",
          to: "9999",
        },
        {
          rate: "131.92",
          to: "10000",
        },
      ],
      stock: "15000",
      images: [
        "/src/assets/Images/products/firefly1.png",
        "/src/assets/Images/products/firefly2.png",
        "/src/assets/Images/products/firefly3.png",
        "/src/assets/Images/products/firefly4.png",
        "/src/assets/Images/products/firefly5.png",
        "/src/assets/Images/products/firefly6.png",
      ],
    },
    count: "10",
  },
  {
    product: {
      name: "Nike shoe for sale",
      description: `Men's Sporty Gym Sneakers Breathable Anti-Slip Lace-Up/Slip-On High Top Winter Spring Autumn Fitness Jogging Mesh Rubber/EVA/PU`,
      minprice: "8000",
      maxprice: "5000",
      minOrder: "6",
      priceRange: [
        {
          rate: "307.81",
          from: "500",
          to: "1999",
        },
        {
          rate: "219.87",
          from: "2000",
          to: "9999",
        },
        {
          rate: "131.92",
          to: "10000",
        },
      ],
      stock: "15000",
      images: [
        "/src/assets/Images/products/firefly1.png",
        "/src/assets/Images/products/firefly2.png",
        "/src/assets/Images/products/firefly3.png",
        "/src/assets/Images/products/firefly4.png",
        "/src/assets/Images/products/firefly5.png",
        "/src/assets/Images/products/firefly6.png",
      ],
    },
    count: "10",
  },
  {
    product: {
      name: "Nike shoe for sale",
      description: `Men's Sporty Gym Sneakers Breathable Anti-Slip Lace-Up/Slip-On High Top Winter Spring Autumn Fitness Jogging Mesh Rubber/EVA/PU`,
      minprice: "8000",
      maxprice: "5000",
      minOrder: "6",
      priceRange: [
        {
          rate: "307.81",
          from: "500",
          to: "1999",
        },
        {
          rate: "219.87",
          from: "2000",
          to: "9999",
        },
        {
          rate: "131.92",
          to: "10000",
        },
      ],
      stock: "15000",
      images: [
        "/src/assets/Images/products/firefly1.png",
        "/src/assets/Images/products/firefly2.png",
        "/src/assets/Images/products/firefly3.png",
        "/src/assets/Images/products/firefly4.png",
        "/src/assets/Images/products/firefly5.png",
        "/src/assets/Images/products/firefly6.png",
      ],
    },
    count: "10",
  },
  {
    product: {
      name: "Nike shoe for sale",
      description: `Men's Sporty Gym Sneakers Breathable Anti-Slip Lace-Up/Slip-On High Top Winter Spring Autumn Fitness Jogging Mesh Rubber/EVA/PU`,
      minprice: "8000",
      maxprice: "5000",
      minOrder: "6",
      priceRange: [
        {
          rate: "307.81",
          from: "500",
          to: "1999",
        },
        {
          rate: "219.87",
          from: "2000",
          to: "9999",
        },
        {
          rate: "131.92",
          to: "10000",
        },
      ],
      stock: "15000",
      images: [
        "/src/assets/Images/products/firefly1.png",
        "/src/assets/Images/products/firefly2.png",
        "/src/assets/Images/products/firefly3.png",
        "/src/assets/Images/products/firefly4.png",
        "/src/assets/Images/products/firefly5.png",
        "/src/assets/Images/products/firefly6.png",
      ],
    },
    count: "10",
  },
  {
    product: {
      name: "Nike shoe for sale",
      description: `Men's Sporty Gym Sneakers Breathable Anti-Slip Lace-Up/Slip-On High Top Winter Spring Autumn Fitness Jogging Mesh Rubber/EVA/PU`,
      minprice: "8000",
      maxprice: "5000",
      minOrder: "6",
      priceRange: [
        {
          rate: "307.81",
          from: "500",
          to: "1999",
        },
        {
          rate: "219.87",
          from: "2000",
          to: "9999",
        },
        {
          rate: "131.92",
          to: "10000",
        },
      ],
      stock: "15000",
      images: [
        "/src/assets/Images/products/firefly1.png",
        "/src/assets/Images/products/firefly2.png",
        "/src/assets/Images/products/firefly3.png",
        "/src/assets/Images/products/firefly4.png",
        "/src/assets/Images/products/firefly5.png",
        "/src/assets/Images/products/firefly6.png",
      ],
    },
    count: "10",
  },
];

export const category = [
  { name: "Loafers", image: "/src/assets/Images/category/loafer.jpg" },
  { name: "Sneakers", image: "/src/assets/Images/category/sneakers.jpg" },
  { name: "Flip-flops", image: "/src/assets/Images/category/flipflops.jpg" },
  { name: "Sports shoes", image: "/src/assets/Images/category/sports-shoes.jpg" },
];
