export const categoryList = [
    
                'Shirt',
                'Mobiles and Laptops',
                'Kurthas',
                'Shoes',
                'Shirt',
                'Mobiles and Laptops',
                'Kurthas',
                'Shoes',
                'Shirt',
                'Mobiles and Laptops',
                'Kurthas',
                'Shoes',
                'Shirt',
                // 'Mobiles and Laptops',
                // 'Kurthas',
                // 'Shoes',
                // 'Shirt',
                // 'Mobiles and Laptops',
                // 'Shirt',
                // 'Mobiles and Laptops',
                // 'Kurthas',
]